Repository malinink/easy-tests, pull requests merged in 2018-04, with the labels that each got.

#286 Fix ignoring of properties in SubjectModelTest
  src/test/java/easytests/core/AbstractMeanBeanTest.java
  src/test/java/easytests/core/models/SubjectModelTest.java
  src/test/java/easytests/support/meanbean/models/IssueStandardModelFactory.java
  src/test/java/easytests/support/meanbean/models/UserModelFactory.java
Labels: pr ready to merge

#296 Refactor IssueStandartServiceTest
  src/test/java/easytests/core/services/IssueStandardsServiceTest.java
  src/test/java/easytests/support/IssueStandardSupport.java
Labels: pr ready for review

#300 Paths and Definitions of Issues.
  src/main/resources/api/api.yaml
Labels: pr ready to merge

#291 Fix ignores in PointModelTest and AnswerModelTest
  src/test/java/easytests/core/AbstractMeanBeanTest.java
  src/test/java/easytests/core/models/AnswerModelTest.java
  src/test/java/easytests/core/models/PointModelTest.java
  src/test/java/easytests/support/meanbean/models/QuestionModelFactory.java
Labels: pr ready to merge

#312 Additions in user api
  src/main/resources/api/api.yaml
Labels: pr ready to merge

#314 Create UsersController,UsersMapper and UsersModel
  src/main/java/easytests/api/v1/controllers/UsersController.java
  src/main/java/easytests/api/v1/mappers/UsersMapper.java
  src/main/java/easytests/api/v1/models/User.java
  src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
Labels: pr ready to merge

#302 Some additions in Question & Answer api
  src/main/resources/api/api.yaml
Labels: pr need some fixes

#319 Add Topic description into api.yaml
  src/main/resources/api/api.yaml
Labels: pr ready for review

#322 Add Subject description into API.yaml
  src/main/resources/api/api.yaml
Labels: pr ready to merge
