Repository malinink/easy-tests, pull requests merged in 2018-05, with the labels that each got.

#328 Add Issue Mapper/Model/Controller/ControllerTest
  src/main/java/easytests/api/v1/controllers/IssuesController.java
  src/main/java/easytests/api/v1/mappers/IssuesMapper.java
  src/main/java/easytests/api/v1/models/Issue.java
  src/test/java/easytests/api/v1/controllers/IssuesControllerTest.java
Labels: pr ready to merge

#341 Add Subject Mapper/Model/Controller/ControllerTest
  src/main/java/easytests/api/v1/controllers/SubjectsController.java
  src/main/java/easytests/api/v1/mappers/SubjectsMapper.java
  src/main/java/easytests/api/v1/models/Subject.java
  src/test/java/easytests/api/v1/controllers/SubjectsControllerTest.java
Labels: pr ready to merge

#336 Add Question Mapper/Model/Controller/ControllerTest
  src/main/java/easytests/api/v1/controllers/QuestionsController.java
  src/main/java/easytests/api/v1/mappers/AdminAnswersMapper.java
  src/main/java/easytests/api/v1/mappers/QuestionsMapper.java
  src/main/java/easytests/api/v1/models/AdminAnswer.java
  src/main/java/easytests/api/v1/models/Question.java
  src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
Labels: pr ready to merge

#318 Refactor QuestionTypeModelTest, QuestionTypesServiceTest
  src/test/java/easytests/core/models/QuestionTypeModelTest.java
  src/test/java/easytests/core/services/QuestionTypesServiceTest.java
Labels: pr ready for review

#304 Some additions in Quiz API
  src/main/resources/api/api.yaml
Labels: pr ready to merge

#352 Create empty Controller/Model/Mapper for Quizzes
  src/main/java/easytests/api/v1/controllers/QuizzesController.java
  src/main/java/easytests/api/v1/mappers/QuizzesMapper.java
  src/main/java/easytests/api/v1/models/Quiz.java
  src/test/java/easytests/api/v1/controllers/QuizzesControllerTest.java
Labels: pr need some fixes

#354 Delete issueUpdate from api.yaml
  src/main/resources/api/api.yaml
Labels: pr ready to merge

#334 List method for IssueController
  src/main/java/easytests/api/v1/controllers/IssuesController.java
  src/main/java/easytests/api/v1/mappers/IssuesMapper.java
  src/test/java/easytests/api/v1/controllers/IssuesControllerTest.java
Labels: pr ready to merge

#348 List method for SubjectsController
  src/main/java/easytests/api/v1/controllers/SubjectsController.java
  src/main/java/easytests/api/v1/mappers/SubjectsMapper.java
  src/test/java/easytests/api/v1/controllers/SubjectsControllerTest.java
Labels: pr ready to merge

#331 List method for TopicsController
  src/main/java/easytests/api/v1/controllers/TopicsController.java
  src/main/java/easytests/api/v1/mappers/TopicsMapper.java
  src/test/java/easytests/api/v1/controllers/TopicsControllerTest.java
Labels: pr ready to merge

#321 Add list method into UsersController
  src/main/java/easytests/api/v1/controllers/UsersController.java
  src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
  src/test/java/easytests/support/UsersSupport.java
Labels: pr ready to merge

#382 Refactor IssueStandartTopicPriorityModel/Service
  src/test/java/easytests/core/models/IssueStandardTopicPriorityModelTest.java
  src/test/java/easytests/core/services/IssueStandardTopicPrioritiesServiceTest.java
Labels: pr ready to merge

#383 Read method for topics
  src/main/java/easytests/api/v1/controllers/TopicsController.java
  src/test/java/easytests/api/v1/controllers/TopicsControllerTest.java
Labels: pr ready to merge

#364 List method for QuizzesController
  src/main/java/easytests/api/v1/controllers/QuizzesController.java
  src/main/java/easytests/api/v1/mappers/QuizzesMapper.java
  src/main/java/easytests/api/v1/models/Quiz.java
  src/main/java/easytests/api/v1/models/Testee.java
  src/main/java/easytests/auth/services/AccessControlLayerService.java
  src/main/java/easytests/auth/services/AccessControlLayerServiceInterface.java
  src/main/resources/api/api.yaml
  src/test/java/easytests/api/v1/controllers/QuizzesControllerTest.java
  src/test/java/easytests/support/JsonSupport.java
Labels: pr ready to merge

#380 Read method for QuestionsController
  src/main/java/easytests/api/v1/controllers/QuestionsController.java
  src/main/java/easytests/api/v1/mappers/QuestionsMapper.java
  src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
Labels: pr ready to merge

#371 List method for QuestionsController
  src/main/java/easytests/api/v1/controllers/QuestionsController.java
  src/main/resources/api/api.yaml
  src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
Labels: pr ready to merge

#385 Read method for IssueController
  src/main/java/easytests/api/v1/controllers/IssuesController.java
  src/test/java/easytests/api/v1/controllers/IssuesControllerTest.java
Labels: pr ready to merge

#386 Read method for Users
  src/main/java/easytests/api/v1/controllers/UsersController.java
  src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
Labels: pr ready to merge

#387 Delete method for IssueController
  src/main/java/easytests/api/v1/controllers/IssuesController.java
  src/test/java/easytests/api/v1/controllers/IssuesControllerTest.java
Labels: pr ready to merge

#391 Read method for Quizzes
  src/main/java/easytests/api/v1/controllers/QuizzesController.java
  src/main/java/easytests/auth/services/AccessControlLayerService.java
  src/main/java/easytests/auth/services/AccessControlLayerServiceInterface.java
  src/test/java/easytests/api/v1/controllers/QuizzesControllerTest.java
Labels: pr ready to merge

#393 ShowMe method for Users
  src/main/java/easytests/api/v1/controllers/UsersController.java
  src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
Labels: pr ready to merge

#379 Create method for SubjectsController
  src/main/java/easytests/api/v1/controllers/SubjectsController.java
  src/main/java/easytests/api/v1/mappers/SubjectsMapper.java
  src/test/java/easytests/api/v1/controllers/SubjectsControllerTest.java
Labels: pr ready to merge

#392 Delete method for Questions
  src/main/java/easytests/api/v1/controllers/QuestionsController.java
  src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
  src/test/java/easytests/support/AnswersSupport.java
Labels: pr ready to merge

#398 Fix ignoring of properties in IssueModelTest
  src/test/java/easytests/core/AbstractMeanBeanTest.java
  src/test/java/easytests/core/models/IssueModelTest.java
  src/test/java/easytests/support/meanbean/models/SubjectModelFactory.java
Labels: pr ready to merge

#375 Create method for UsersController and Test
  src/main/java/easytests/api/v1/controllers/UsersController.java
  src/test/java/easytests/api/v1/controllers/UsersControllerTest.java
  src/test/java/easytests/support/UsersSupport.java
Labels: pr ready to merge

#394 Delete method for TopicsController
  src/main/java/easytests/api/v1/controllers/TopicsController.java
  src/test/java/easytests/api/v1/controllers/TopicsControllerTest.java
Labels: pr ready to merge

#384 Delete method for SubjectController
  src/main/java/easytests/api/v1/controllers/SubjectsController.java
  src/test/java/easytests/api/v1/controllers/SubjectsControllerTest.java
Labels: pr ready to merge

#400 Update method for TopicsController
  src/main/java/easytests/api/v1/controllers/TopicsController.java
  src/main/java/easytests/api/v1/mappers/TopicsMapper.java
  src/test/java/easytests/api/v1/controllers/TopicsControllerTest.java
Labels: pr ready to merge

#390 Update method for SubjectsController
  src/main/java/easytests/api/v1/controllers/SubjectsController.java
  src/main/java/easytests/api/v1/mappers/SubjectsMapper.java
  src/test/java/easytests/api/v1/controllers/SubjectsControllerTest.java
  src/test/java/easytests/support/SubjectsSupport.java
Labels: pr ready to merge

#395 Create method for TopicsController
  src/main/java/easytests/api/v1/controllers/TopicsController.java
  src/main/java/easytests/api/v1/mappers/TopicsMapper.java
  src/test/java/easytests/api/v1/controllers/TopicsControllerTest.java
Labels: pr ready to merge

#396 Create method for QuestionController
  src/main/java/easytests/api/v1/controllers/QuestionsController.java
  src/main/java/easytests/api/v1/mappers/AdminAnswersMapper.java
  src/main/java/easytests/api/v1/mappers/QuestionsMapper.java
  src/main/java/easytests/api/v1/validators/AnswersValidator.java
  src/main/java/easytests/api/v1/validators/QuiestionsValidator.java
  src/test/java/easytests/api/v1/controllers/QuestionsControllerTest.java
  src/test/java/easytests/support/AnswersSupport.java
Labels: pr ready to merge
